services:
  aws-storage-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_PROFILE=default
    restart: unless-stopped
    # Credentials path will be added by setup script in docker-compose.override.yml
